### ISSUE TITLE
This should list the build-dep command to prepare the environment

### ISSUE THREAD

**Issue by bw-matthew** [matthewfranglen/build-vim#2]
In debian the `sudo apt-get build-dep vim` command will install the dependencies required to build vim. This should be listed in the readme.

**Comment by matthewfranglen** [comment]
Fixed by https://github.com/matthewfranglen/build-vim/commit/f11a3888a2b70a7d66a22daca4b9fc9a2e6b8003. Made a mistake in the commit message.
